'use strict';

const axios = require('axios');
const { config } = require('../config');
const { createLogger } = require('../utils/logger');

const logger = createLogger('AIService');

/**
 * The shape of a real AI service response.
 *
 * {
 *   files_to_update: Array<{ path: string, content: string }>,
 *   pr_title: string,
 *   pr_body: string,
 * }
 */

const MOCK_RESPONSE = {
  files_to_update: [
    {
      path: 'docs/api.md',
      content:
        '# Updated API Documentation\n\nNew endpoint added based on latest commit.\n\n' +
        '> This file was auto-generated by **AutoDocs**.\n',
    },
  ],
  pr_title: '📝 AutoDocs: Documentation Updated',
  pr_body:
    'Automated documentation update based on latest commit.\n\n' +
    '_Generated by [AutoDocs](https://github.com/apps/autodocs)_',
};

/**
 * Sends the repository change payload to the Python AI service.
 * Falls back to a mock response when the service is unreachable.
 *
 * @param {{
 *   repo: string,
 *   owner: string,
 *   branch: string,
 *   installationId: string|number,
 *   commitMessage: string,
 *   commitId: string,
 *   changedFiles: string[]
 * }} payload
 *
 * @returns {Promise<{
 *   files_to_update: Array<{ path: string, content: string }>,
 *   pr_title: string,
 *   pr_body: string
 * }>}
 */
async function sendRepoChangeToAI(payload) {
  const endpoint = `${config.pythonAI.baseUrl}/process-change`;

  logger.info('Sending payload to AI service', {
    endpoint,
    repo: payload.repo,
    changedFiles: payload.changedFiles.length,
  });

  try {
    const response = await axios.post(endpoint, payload, {
      timeout: config.pythonAI.timeoutMs,
      headers: {
        'Content-Type': 'application/json',
        'X-AUTODOCS-SECRET': config.pythonAI.sharedSecret,
      },
    });

    logger.info('AI service responded successfully', {
      repo: payload.repo,
      filesReturned: response.data?.files_to_update?.length ?? 0,
    });

    return response.data;
  } catch (err) {
    const isNetworkError =
      err.code === 'ECONNREFUSED' ||
      err.code === 'ENOTFOUND' ||
      err.code === 'ETIMEDOUT' ||
      err.response?.status >= 500;

    if (isNetworkError) {
      logger.warn('AI service unavailable — using mock response', {
        code: err.code,
        status: err.response?.status,
        message: err.message,
      });
      return MOCK_RESPONSE;
    }

    // Non-network error (e.g. 400 bad request) — re-throw
    logger.error('AI service returned an error', {
      status: err.response?.status,
      data: err.response?.data,
    });
    throw err;
  }
}

module.exports = { sendRepoChangeToAI };
